branch-defaults:
  main:
    environment: flask-londonbikeshare-env
global:
  application_name: flask-londonbikeshare
  branch: null
  default_ec2_keyname: aws-eb-lb
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
